this file contains explaination for somelines which the writer thinks someone new reading the code cannot understand

line 57 - 72:
	if the variable 'QEMU' is not defined then do this
	execute the commands after the shell keywrd on the system default shell and capture the standard output of that shell
	a new shell will be forked for this and the stdout of that shell would be this make
	the output fo each 'which' is given to character special file /dev/null so that it doesnt get printed


line 94:
	input file = /dev/zero
	output file = xv6.img
	copy 10000 blocks from input file to output file
	/dev/zero is a character special file from which 'n' number of null(0x00) can be read
line 94:
	intput file = bootblock 
	output file = xv6.img
	do not truncate the output file and copy all bytes from input file to output file

line 96:
	input file = kernel
	output file = xv6.img
	do not truncate the output file, skip first 512 bytes of output file and start copying from 513th byte


