#! /usr/bin/bash

echo "git fetch"
git fetch
echo "git pull"
git pull
echo "git status"
git status
echo "git add"
git add *
echo "git commit"
read -p "commit msg --> " msg
git commit -m "$msg"
echo "git push"
git push
